### PR TITLE
Add data state

### PR DESCRIPTION
**Pull request by bedeoverend**
Adds in the data state as per #35.

- [x] Add data reducer state to track all simpla data
- [x] `get` / `set` / `remove` should operate on state before touching API
- [x] `get` where no data state exists should hydrate from API
- [x] `save` state should hold all data and whether they differ from local state to API state
- [x] `save` method should `set` / `remove` data to API based on if changes have been made

### CODE REVIEW

**Comment by bedeoverend** [comment]
@seaneking I also added the change of observe and observeState, they're a big breaking change for Simpla however - `simpla-img` and `simpla-text` right now use `Simpla.observe` which means we couldn't merge this until all elements are ready to be upgraded. Can you see an issue with this? They'll need to be updated to use this anyway, in conjunction with moving to Polymer 2

**Comment by seaneking** [comment]
Yep this will have to happen after simpla-text and simpla-img are refactored later this year

**Comment by seaneking** [comment]
Or if it needs to happen before then we can just temp patch img and text to `observeState` (or whatever we settle on for that method name)

**Comment by bedeoverend** [comment]
Closing this in favour of using an overall v2 branch

**Pull request closed without merging**
